### ISSUE TITLE
Dossier returns 404

### ISSUE THREAD

**Issue by alsahawneh** [jordanopensource/portal-web#193]
**Describe the bug**
A 404 error occurs whenever you try to access the dossier.

**To Reproduce**
1. Go to `josa.ngo`.
2. `/dossier`.
3. See error.

**Expected behavior**
 Dossier should be accessed without errors.

**Screenshots**
![Screenshot 2022-03-30 at 21-05-46 Jordan Open Source Association](https://user-images.githubusercontent.com/79845228/160902992-0f8e4d96-9a31-4d21-844e-11c367121bf4.png)

**Comment by mahasneh** [comment]
There is no page as [https://josa.ngo/dossier](https://josa.ngo/dossier), what do you expect to return in any case?

**Comment by alsahawneh** [comment]
> There is no page as https://josa.ngo/dossier, what do you expect to return in any case?

What's the path for our dossiers? As far as I know it is `/dossier`, isn't it?

**Comment by thread-koder** [comment]
@mahasneh @alsahawneh Hope you are having a nice day, as there is no main page or a root for the `/dossier` route by design,  this is the correct and desired behavior of the route, you can access the desired dossier by using `/dossier/the-title-of-the-dossier` if you have any more questions please be free to reach out and I will gladly answer.

**Comment by alsahawneh** [comment]
> @mahasneh @alsahawneh Hope you are having a nice day, as there is no main page or a root for the `/dossier` route by design, this is the correct and desired behavior of the route, you can access the desired dossier by using `/dossier/the-title-of-the-dossier` if you have any more questions please be free to reach out and I will gladly answer.

Makes sense. Thanks a lot!
