### ISSUE TITLE
If a blog post is featured, it should not show in the list below

### ISSUE THREAD

**Issue by mahasneh** [jordanopensource/portal-web#293]
If a blog post is set as featured, it should not show again in the list below, the image shows the issue:
![image](https://user-images.githubusercontent.com/7326249/115995614-9d975800-a5e4-11eb-8c14-5e7d851cabca.png)

**Comment by ZaidBarghouthi** [comment]
I've been looking at the way the blog page is implemented. There are some problems. 

1. The components `blogList` is used twice on the blog page. First it has a featured flag so it fetches a featured post. The second time it fetches the normal list. That makes it not so straight forward to filter the featured post as each section is in a different component.
2. Not directly related, but the page initiated 4 API calls. 2 for featured and 2 for the remaining, because a second request is used to get the count by getting all the posts! Which is not ideal for long term use (get 100 post with all their data just to get the count)

### Possible Solutions
1. One work around is to send the featured post id as a prop to the second blog list and use it to filter. The featured article might appear in the list and then disappear, which is not ideal. Moreover, some pages will contain X posts and others will contain X - 1 posts. Again, not ideal.

2. I'm not sure how the API is implemented. Ideally, we need to get a featured article [or a list of featured articles] + a paginated list not containing the featured article(s). That might need significant changes on the API. Not ideal.

I'm included to go forward and implement solution 1. 

What do you guys think?

**Comment by mahasneh** [comment]
Regarding point 2, I would suggest to open a new issue for that.

**Comment by wissamataleh** [comment]
> I've been looking at the way the blog page is implemented. There are some problems.
> 
>     1. The component `blogList` is used twice on the blog page. First it has a featured flag so it fetches a featured post. The second time it fetches the normal list. That makes it not so straight forward to filter the featured post as each section is in a different component.
> 
>     2. Not directly related, but the page makes 4 API calls. 2 for featured and 2 for the remaining, because a second request is used to get the count by getting all the posts! Which is not ideal for long term use (get 100 post with all their data just to get the count)
> 
> 
> ### Possible Solutions
> 
>     1. One work around is to send the featured post id as a prop to the second blog list and use it to filter. The featured article might appear in the list and then disappear, which is not ideal. Moreover, some pages will contain X posts and others will contain X - 1 posts. Again, not ideal.
> 
>     2. I'm not sure how the API is implemented. Ideally, we need to get a featured article [or a list of featured articles] + a paginated list not containing the featured article(s). That might need significant changes on the API. Not ideal.
> 
> 
> I'm included to go forward and implement solution 1.
> 
> What do you guys think?

For point 1: Vuex store solves this.
For point 2: Data fetching accros the website will be optimized in future releases.
